# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cambrian_pb2 as cambrian__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cambrian_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/cambrian.Orchestrator/Execute',
                request_serializer=cambrian__pb2.Handoff.SerializeToString,
                response_deserializer=cambrian__pb2.Handoff.FromString,
                _registered_method=True)
        self.RequestProposal = channel.unary_unary(
                '/cambrian.Orchestrator/RequestProposal',
                request_serializer=cambrian__pb2.AuctionTask.SerializeToString,
                response_deserializer=cambrian__pb2.AgentProposal.FromString,
                _registered_method=True)
        self.QueryMemory = channel.unary_unary(
                '/cambrian.Orchestrator/QueryMemory',
                request_serializer=cambrian__pb2.MemoryRequest.SerializeToString,
                response_deserializer=cambrian__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/cambrian.Orchestrator/ChatStream',
                request_serializer=cambrian__pb2.Handoff.SerializeToString,
                response_deserializer=cambrian__pb2.SymbiosisEvent.FromString,
                _registered_method=True)
        self.SignalStream = channel.stream_stream(
                '/cambrian.Orchestrator/SignalStream',
                request_serializer=cambrian__pb2.Handoff.SerializeToString,
                response_deserializer=cambrian__pb2.SymbiosisEvent.FromString,
                _registered_method=True)
        self.GenerateViaModelStream = channel.unary_stream(
                '/cambrian.Orchestrator/GenerateViaModelStream',
                request_serializer=cambrian__pb2.GenerateStreamRequest.SerializeToString,
                response_deserializer=cambrian__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.GetContextNode = channel.unary_unary(
                '/cambrian.Orchestrator/GetContextNode',
                request_serializer=cambrian__pb2.ContextNodeRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ContextNodeResponse.FromString,
                _registered_method=True)
        self.PutContextNode = channel.unary_unary(
                '/cambrian.Orchestrator/PutContextNode',
                request_serializer=cambrian__pb2.PutContextNodeRequest.SerializeToString,
                response_deserializer=cambrian__pb2.PutContextNodeResponse.FromString,
                _registered_method=True)
        self.RegisterWatch = channel.unary_unary(
                '/cambrian.Orchestrator/RegisterWatch',
                request_serializer=cambrian__pb2.RegisterWatchRequest.SerializeToString,
                response_deserializer=cambrian__pb2.RegisterWatchResponse.FromString,
                _registered_method=True)
        self.ListWatches = channel.unary_unary(
                '/cambrian.Orchestrator/ListWatches',
                request_serializer=cambrian__pb2.ListWatchesRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ListWatchesResponse.FromString,
                _registered_method=True)
        self.DeleteWatch = channel.unary_unary(
                '/cambrian.Orchestrator/DeleteWatch',
                request_serializer=cambrian__pb2.DeleteWatchRequest.SerializeToString,
                response_deserializer=cambrian__pb2.DeleteWatchResponse.FromString,
                _registered_method=True)
        self.SetWatchActive = channel.unary_unary(
                '/cambrian.Orchestrator/SetWatchActive',
                request_serializer=cambrian__pb2.SetWatchActiveRequest.SerializeToString,
                response_deserializer=cambrian__pb2.SetWatchActiveResponse.FromString,
                _registered_method=True)
        self.UploadArtifact = channel.unary_unary(
                '/cambrian.Orchestrator/UploadArtifact',
                request_serializer=cambrian__pb2.UploadArtifactRequest.SerializeToString,
                response_deserializer=cambrian__pb2.UploadArtifactResponse.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/cambrian.Orchestrator/GetArtifact',
                request_serializer=cambrian__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=cambrian__pb2.GetArtifactResponse.FromString,
                _registered_method=True)
        self.ListStepArtifacts = channel.unary_unary(
                '/cambrian.Orchestrator/ListStepArtifacts',
                request_serializer=cambrian__pb2.ListStepArtifactsRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ListStepArtifactsResponse.FromString,
                _registered_method=True)
        self.IngestMemory = channel.unary_unary(
                '/cambrian.Orchestrator/IngestMemory',
                request_serializer=cambrian__pb2.IngestMemoryRequest.SerializeToString,
                response_deserializer=cambrian__pb2.IngestMemoryResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/cambrian.Orchestrator/ExecuteTool',
                request_serializer=cambrian__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ExecuteToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/cambrian.Orchestrator/ListTools',
                request_serializer=cambrian__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/cambrian.Orchestrator/ListSkills',
                request_serializer=cambrian__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/cambrian.Orchestrator/Embed',
                request_serializer=cambrian__pb2.EmbedRequest.SerializeToString,
                response_deserializer=cambrian__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.WatchApprovals = channel.unary_stream(
                '/cambrian.Orchestrator/WatchApprovals',
                request_serializer=cambrian__pb2.WatchApprovalsRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ApprovalRequest.FromString,
                _registered_method=True)
        self.SubmitApprovalDecision = channel.unary_unary(
                '/cambrian.Orchestrator/SubmitApprovalDecision',
                request_serializer=cambrian__pb2.ApprovalDecisionRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ApprovalDecisionResponse.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """The main method where the agent receives and processes a task (if the Orchestrator also implements this service)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestProposal(self, request, context):
        """Auction / Qualified-Volunteering Model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemory(self, request, context):
        """Shared LTM semantic query — proxied through Substrate with ACL enforcement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """Bi-directional TUI shell stream. Upstream: user commands (Handoff).
        Downstream: real-time telemetry envelope (SymbiosisEvent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalStream(self, request_iterator, context):
        """Proactive neural signal stream. Upstream: agent signals (Handoff with _signal_type).
        Downstream: plan execution telemetry (SymbiosisEvent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateViaModelStream(self, request, context):
        """Managed LLM call: the Substrate acts as a metered proxy, forwarding chunks
        from the allocated TraitModel to the agent with per-chunk token accounting.
        ADR-0018.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContextNode(self, request, context):
        """Resolve a CID from the ContentStore (step results) or LTM pgvector.
        Used by agents' assemble_context(fetch_fn=agent.substrate.get_context_node).
        Returns empty data when the CID is unknown. ADR-0022 Phase 3.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutContextNode(self, request, context):
        """Store a content blob in the ephemeral ContentStore and return its CID
        (ADR-0048 D4/R7). Used by an agent's working memory to offload a large block
        and carry a {gist + cid} pointer; the blob is owner-stamped with the caller's
        session so reads are gated (GetContextNode). Idempotent (content-addressed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWatch(self, request, context):
        """WatchConfig CRUD — premium build only. ADR-0032.
        Create or replace a reactive rule. Returns the persisted config ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWatches(self, request, context):
        """List all registered WatchConfigs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWatch(self, request, context):
        """Delete a WatchConfig by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWatchActive(self, request, context):
        """Enable or disable a WatchConfig without deleting it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadArtifact(self, request, context):
        """Artifact storage with ADR-0034 tag-based access scoping. REQ-SDK-007c.
        Upload validates classification tags against the writer's scope + controlled
        vocabulary and kernel-stamps provenance before persisting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Get an artifact by content hash; returns empty when the caller's effective
        scope does not permit the artifact's tags (fail-closed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStepArtifacts(self, request, context):
        """List artifacts produced by a session+step, scope-filtered for the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMemory(self, request, context):
        """memory.remember() write-back. The kernel DERIVES classification from the
        agent's DefaultWriteTags (ADR-0035 C2); req.tags is a narrow-only hint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """ADR-0039: kernel-owned tool registry. A cognitive agent invokes a granted
        system tool with LLM-marshalled args; the kernel authorizes (grant +
        resource policy + data scope + approval) and runs it in a confined process.
        The principal is taken from x-agent-id gRPC metadata, never from the body.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """ADR-0039: the system tools the calling agent (x-agent-id) may invoke, for
        building the agent's closed ReAct tool menu. Advisory only — ExecuteTool
        still authorizes every call. Honors the unrestricted bypass.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """ADR-0046: the system skills the calling agent (x-agent-id) may load, for the
        agent's [skills] menu section. Tier-1 (summary) by default; Tier-2 (full
        instructions) for a named skill via use_skill. Scope-gated; agent-local
        skills are NOT served here (they are SDK-local, the @tools analog).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """ADR-0041: embed text into a vector using the kernel's embedder, for the
        agent's Local Recurrent Workspace relevance ranking. Read-only; no auth impact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchApprovals(self, request, context):
        """Operator-plane: stream pending dangerous-tool approval requests (ADR-0039 D10).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitApprovalDecision(self, request, context):
        """Operator-plane: submit an approve/deny decision for a pending request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=cambrian__pb2.Handoff.FromString,
                    response_serializer=cambrian__pb2.Handoff.SerializeToString,
            ),
            'RequestProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestProposal,
                    request_deserializer=cambrian__pb2.AuctionTask.FromString,
                    response_serializer=cambrian__pb2.AgentProposal.SerializeToString,
            ),
            'QueryMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemory,
                    request_deserializer=cambrian__pb2.MemoryRequest.FromString,
                    response_serializer=cambrian__pb2.MemoryResponse.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=cambrian__pb2.Handoff.FromString,
                    response_serializer=cambrian__pb2.SymbiosisEvent.SerializeToString,
            ),
            'SignalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SignalStream,
                    request_deserializer=cambrian__pb2.Handoff.FromString,
                    response_serializer=cambrian__pb2.SymbiosisEvent.SerializeToString,
            ),
            'GenerateViaModelStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateViaModelStream,
                    request_deserializer=cambrian__pb2.GenerateStreamRequest.FromString,
                    response_serializer=cambrian__pb2.GenerateChunk.SerializeToString,
            ),
            'GetContextNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContextNode,
                    request_deserializer=cambrian__pb2.ContextNodeRequest.FromString,
                    response_serializer=cambrian__pb2.ContextNodeResponse.SerializeToString,
            ),
            'PutContextNode': grpc.unary_unary_rpc_method_handler(
                    servicer.PutContextNode,
                    request_deserializer=cambrian__pb2.PutContextNodeRequest.FromString,
                    response_serializer=cambrian__pb2.PutContextNodeResponse.SerializeToString,
            ),
            'RegisterWatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWatch,
                    request_deserializer=cambrian__pb2.RegisterWatchRequest.FromString,
                    response_serializer=cambrian__pb2.RegisterWatchResponse.SerializeToString,
            ),
            'ListWatches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWatches,
                    request_deserializer=cambrian__pb2.ListWatchesRequest.FromString,
                    response_serializer=cambrian__pb2.ListWatchesResponse.SerializeToString,
            ),
            'DeleteWatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWatch,
                    request_deserializer=cambrian__pb2.DeleteWatchRequest.FromString,
                    response_serializer=cambrian__pb2.DeleteWatchResponse.SerializeToString,
            ),
            'SetWatchActive': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWatchActive,
                    request_deserializer=cambrian__pb2.SetWatchActiveRequest.FromString,
                    response_serializer=cambrian__pb2.SetWatchActiveResponse.SerializeToString,
            ),
            'UploadArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadArtifact,
                    request_deserializer=cambrian__pb2.UploadArtifactRequest.FromString,
                    response_serializer=cambrian__pb2.UploadArtifactResponse.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=cambrian__pb2.GetArtifactRequest.FromString,
                    response_serializer=cambrian__pb2.GetArtifactResponse.SerializeToString,
            ),
            'ListStepArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStepArtifacts,
                    request_deserializer=cambrian__pb2.ListStepArtifactsRequest.FromString,
                    response_serializer=cambrian__pb2.ListStepArtifactsResponse.SerializeToString,
            ),
            'IngestMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMemory,
                    request_deserializer=cambrian__pb2.IngestMemoryRequest.FromString,
                    response_serializer=cambrian__pb2.IngestMemoryResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=cambrian__pb2.ExecuteToolRequest.FromString,
                    response_serializer=cambrian__pb2.ExecuteToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=cambrian__pb2.ListToolsRequest.FromString,
                    response_serializer=cambrian__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=cambrian__pb2.ListSkillsRequest.FromString,
                    response_serializer=cambrian__pb2.ListSkillsResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=cambrian__pb2.EmbedRequest.FromString,
                    response_serializer=cambrian__pb2.EmbedResponse.SerializeToString,
            ),
            'WatchApprovals': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchApprovals,
                    request_deserializer=cambrian__pb2.WatchApprovalsRequest.FromString,
                    response_serializer=cambrian__pb2.ApprovalRequest.SerializeToString,
            ),
            'SubmitApprovalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitApprovalDecision,
                    request_deserializer=cambrian__pb2.ApprovalDecisionRequest.FromString,
                    response_serializer=cambrian__pb2.ApprovalDecisionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cambrian.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cambrian.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/Execute',
            cambrian__pb2.Handoff.SerializeToString,
            cambrian__pb2.Handoff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/RequestProposal',
            cambrian__pb2.AuctionTask.SerializeToString,
            cambrian__pb2.AgentProposal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/QueryMemory',
            cambrian__pb2.MemoryRequest.SerializeToString,
            cambrian__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cambrian.Orchestrator/ChatStream',
            cambrian__pb2.Handoff.SerializeToString,
            cambrian__pb2.SymbiosisEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cambrian.Orchestrator/SignalStream',
            cambrian__pb2.Handoff.SerializeToString,
            cambrian__pb2.SymbiosisEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateViaModelStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cambrian.Orchestrator/GenerateViaModelStream',
            cambrian__pb2.GenerateStreamRequest.SerializeToString,
            cambrian__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContextNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/GetContextNode',
            cambrian__pb2.ContextNodeRequest.SerializeToString,
            cambrian__pb2.ContextNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutContextNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/PutContextNode',
            cambrian__pb2.PutContextNodeRequest.SerializeToString,
            cambrian__pb2.PutContextNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/RegisterWatch',
            cambrian__pb2.RegisterWatchRequest.SerializeToString,
            cambrian__pb2.RegisterWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/ListWatches',
            cambrian__pb2.ListWatchesRequest.SerializeToString,
            cambrian__pb2.ListWatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/DeleteWatch',
            cambrian__pb2.DeleteWatchRequest.SerializeToString,
            cambrian__pb2.DeleteWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWatchActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/SetWatchActive',
            cambrian__pb2.SetWatchActiveRequest.SerializeToString,
            cambrian__pb2.SetWatchActiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/UploadArtifact',
            cambrian__pb2.UploadArtifactRequest.SerializeToString,
            cambrian__pb2.UploadArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/GetArtifact',
            cambrian__pb2.GetArtifactRequest.SerializeToString,
            cambrian__pb2.GetArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStepArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/ListStepArtifacts',
            cambrian__pb2.ListStepArtifactsRequest.SerializeToString,
            cambrian__pb2.ListStepArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/IngestMemory',
            cambrian__pb2.IngestMemoryRequest.SerializeToString,
            cambrian__pb2.IngestMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/ExecuteTool',
            cambrian__pb2.ExecuteToolRequest.SerializeToString,
            cambrian__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/ListTools',
            cambrian__pb2.ListToolsRequest.SerializeToString,
            cambrian__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/ListSkills',
            cambrian__pb2.ListSkillsRequest.SerializeToString,
            cambrian__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/Embed',
            cambrian__pb2.EmbedRequest.SerializeToString,
            cambrian__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cambrian.Orchestrator/WatchApprovals',
            cambrian__pb2.WatchApprovalsRequest.SerializeToString,
            cambrian__pb2.ApprovalRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitApprovalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.Orchestrator/SubmitApprovalDecision',
            cambrian__pb2.ApprovalDecisionRequest.SerializeToString,
            cambrian__pb2.ApprovalDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Service that agents register with, or that agents implement (AgentService)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestProposal = channel.unary_unary(
                '/cambrian.AgentService/RequestProposal',
                request_serializer=cambrian__pb2.ProposalRequest.SerializeToString,
                response_deserializer=cambrian__pb2.ProposalResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/cambrian.AgentService/Execute',
                request_serializer=cambrian__pb2.Handoff.SerializeToString,
                response_deserializer=cambrian__pb2.Handoff.FromString,
                _registered_method=True)
        self.VerifyOutput = channel.unary_unary(
                '/cambrian.AgentService/VerifyOutput',
                request_serializer=cambrian__pb2.VerifyRequest.SerializeToString,
                response_deserializer=cambrian__pb2.VerifyResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Service that agents register with, or that agents implement (AgentService)
    """

    def RequestProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestProposal,
                    request_deserializer=cambrian__pb2.ProposalRequest.FromString,
                    response_serializer=cambrian__pb2.ProposalResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=cambrian__pb2.Handoff.FromString,
                    response_serializer=cambrian__pb2.Handoff.SerializeToString,
            ),
            'VerifyOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOutput,
                    request_deserializer=cambrian__pb2.VerifyRequest.FromString,
                    response_serializer=cambrian__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cambrian.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cambrian.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Service that agents register with, or that agents implement (AgentService)
    """

    @staticmethod
    def RequestProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.AgentService/RequestProposal',
            cambrian__pb2.ProposalRequest.SerializeToString,
            cambrian__pb2.ProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.AgentService/Execute',
            cambrian__pb2.Handoff.SerializeToString,
            cambrian__pb2.Handoff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cambrian.AgentService/VerifyOutput',
            cambrian__pb2.VerifyRequest.SerializeToString,
            cambrian__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
